name: Database-CI

on:
  workflow_dispatch:
  #workflow_call:
    #secrets:
      #Workflow2_PAT_TOKEN_GITHUB:
        #required: true
env:
  JAVA_VERSION: '17' 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
jobs:
  build:
    name: java ci sonar build
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout from Repo
        uses: actions/checkout@v3
          
      - name: Setup Java Sdk ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'
          
      #- name: Cache SonarQube packages
        #uses: actions/cache@v3
        #with:
         # path: ~/.sonar/cache
          #key: ${{ runner.os }}-sonar
          #restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Run SonarQube Scan
        run: |
          echo "SONAR URL - > " ${{vars.SONAR_HOST_URL}}
          export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          export SONAR_HOST_URL=${{vars.SONAR_HOST_URL}}
          export GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}
           mvn install sonar:sonar \
         
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        
       
      
